[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Our Mission"
  url = "/mission"
  weight = 2

[[main]]
  name = "Youth"
  url = "/youth"
  weight = 3

[[main]]
  name = "Parents"
  url = "/parents"
  weight = 4

[[main]]
  name = "Volunteer"
  url = "/volunteer"
  weight = 5

[[main]]
  name = "Donate"
  url = "/donate"
  weight = 6

[[main]]
  name = "Partners"
  url = "/partners"
  weight = 7

[[main]]
  name = "Contact Us"
  url = "/contact"
  weight = 8
